use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::PathBuf;

// 简单的 Pascal DB 文本解析：接受以 DB 或 db 开头的行，解析 $xx 或 decimal 数字、逗号分隔
fn parse_pascal_db_text(s: &str) -> Vec<u8> {
    let mut out = Vec::new();
    for line in s.lines() {
        let l = line.trim_start();
        if !(l.starts_with("db") || l.starts_with("DB")) {
            continue;
        }
        let rest = &l[2..];
        for tok in rest.split(|c: char| c == ',' || c.is_whitespace()) {
            let t = tok.trim().trim_end_matches(',');
            if t.is_empty() {
                continue;
            }
            if let Some(hex) = t.strip_prefix('$') {
                if let Ok(v) = u8::from_str_radix(hex, 16) {
                    out.push(v);
                    continue;
                }
            }
            if let Ok(v) = t.parse::<u8>() {
                out.push(v);
                continue;
            }
        }
    }
    out
}

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed=assets");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets_dir = manifest_dir.join("assets");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let generated = out_dir.join("generated_assets.rs");
    let mut f = File::create(&generated)?;

    writeln!(f, "// Auto-generated by build.rs - do not edit\n")?;
    writeln!(
        f,
        "// This module exposes static byte arrays for assets parsed at compile time.\n"
    )?;

    // Background files: BOGEN.BK, BOGEN7.BK, BOGEN26.BK, MOUNT.BK
    let background_files = ["BOGEN.BK", "BOGEN7.BK", "BOGEN26.BK", "MOUNT.BK"];
    for name in &background_files {
        let path = assets_dir.join(name);
        if path.exists() {
            let data = fs::read_to_string(&path).unwrap_or_else(|_| String::new());
            let bytes = parse_pascal_db_text(&data);
            writeln!(
                f,
                "pub static {}: &[u8] = &{:?};",
                name.replace('.', "_").to_uppercase(),
                bytes
            )?;
        } else {
            writeln!(f, "// missing asset: {}", name)?;
            writeln!(
                f,
                "pub static {}: &[u8] = &[];",
                name.replace('.', "_").to_uppercase()
            )?;
        }
    }

    // Sprites directory: assets/sprites - for each file with ext '.$..' or '.000' etc, produce a static byte array
    let sprites_dir = assets_dir.join("sprites");
    if sprites_dir.exists() {
        // collect mapping entries for lookup function
        let mut mappings: Vec<(String, String)> = Vec::new();
        for entry in fs::read_dir(&sprites_dir)? {
            let entry = entry?;
            let p = entry.path();
            if !p.is_file() {
                continue;
            }
            if let Some(name) = p.file_name().and_then(|n| n.to_str()) {
                // produce a Rust identifier safe name
                let ident = name.replace('.', "_").replace('$', "DOLLAR");
                let const_name = ident.to_uppercase();
                if name.contains(".$")
                    || name.ends_with(".000")
                    || name.ends_with(".001")
                    || name.ends_with(".002")
                    || name.ends_with(".003")
                {
                    // read as text and try parse DB, otherwise read as binary
                    let content = fs::read(&p)?;
                    // Heuristic: if file contains ascii printable and 'db' token, parse as text
                    let texty = std::str::from_utf8(&content).ok();
                    if let Some(t) = texty {
                        if t.contains("db") || t.contains("DB") {
                            let bytes = parse_pascal_db_text(t);
                            writeln!(f, "pub static {}: &[u8] = &{:?};", const_name, bytes)?;
                            mappings.push((name.to_string(), const_name));
                            continue;
                        }
                    }
                    // fallback: raw bytes
                    writeln!(f, "pub static {}: &[u8] = &{:?};", const_name, content)?;
                    mappings.push((name.to_string(), const_name));
                }
            }
        }

        // emit lookup function for sprite assets
        writeln!(
            f,
            "\n/// Lookup generated asset by filename (e.g. \"PALPILL.$00\" or \"PALPILL.000\")"
        )?;
        writeln!(
            f,
            "pub fn get_generated_asset(name: &str) -> Option<&'static [u8]> {{"
        )?;
        writeln!(f, "    match name {{")?;
        for (fname, const_name) in mappings {
            writeln!(f, "        \"{}\" => Some({}),", fname, const_name)?;
        }
        writeln!(f, "        _ => None,")?;
        writeln!(f, "    }}")?;
        writeln!(f, "}}")?;
    }

    // Generate MPAL256 palette as a static constant array
    let mpal256_path = sprites_dir.join("MPAL256");
    if mpal256_path.exists() {
        let data = fs::read_to_string(&mpal256_path).unwrap_or_else(|_| String::new());
        let bytes = parse_pascal_db_text(&data);

        // Convert flat bytes to [[u8; 3]; 256] palette format
        writeln!(
            f,
            "\n/// MPAL256 palette: 256 RGB entries (6-bit VGA values)"
        )?;
        writeln!(f, "pub static MPAL256_PALETTE: [[u8; 3]; 256] = [")?;
        for i in 0..256 {
            let r = bytes.get(i * 3).copied().unwrap_or(0);
            let g = bytes.get(i * 3 + 1).copied().unwrap_or(0);
            let b = bytes.get(i * 3 + 2).copied().unwrap_or(0);
            writeln!(f, "    [{}, {}, {}],", r, g, b)?;
        }
        writeln!(f, "];")?;
    }

    // write a helper constant with module doc
    writeln!(f, "\n// end of generated file")?;

    // Tell Cargo to include the generated file path via OUT_DIR
    println!("cargo:warning=generated assets at {}", generated.display());

    // 获取目标操作系统 (交叉编译时需要用环境变量而不是 cfg)
    let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();

    // Windows: 嵌入应用程序图标 (仅当目标是 Windows 时)
    if target_os == "windows" {
        let rc_path = assets_dir.join("mario.rc");
        if rc_path.exists() {
            let _ = embed_resource::compile(&rc_path, embed_resource::NONE);
        }

        // Windows XP 兼容性：链接 YY-Thunks
        // 当设置环境变量 MARIO_XP_COMPAT=1 时启用
        if env::var("MARIO_XP_COMPAT").is_ok() {
            let yy_thunks_dir = manifest_dir.join("vendor").join("yy-thunks").join("objs");

            // 根据目标架构选择对应的 obj 文件
            let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
            let (arch_dir, subsystem_version) = match target_arch.as_str() {
                "x86" => ("x86", "5.01"),    // Windows XP (x86)
                "x86_64" => ("x64", "5.02"), // Windows Server 2003 / XP x64 Edition
                _ => ("x64", "5.02"),
            };

            let obj_path = yy_thunks_dir.join(arch_dir).join("YY_Thunks_for_WinXP.obj");

            if obj_path.exists() {
                // 链接 YY-Thunks obj 文件
                println!("cargo:rustc-link-arg={}", obj_path.display());
                // 设置子系统版本以支持 XP
                println!(
                    "cargo:rustc-link-arg=/SUBSYSTEM:WINDOWS,{}",
                    subsystem_version
                );
                println!(
                    "cargo:warning=YY-Thunks enabled for Windows XP compatibility ({})",
                    arch_dir
                );
            } else {
                println!(
                    "cargo:warning=YY-Thunks obj not found at: {}",
                    obj_path.display()
                );
            }
        }
    }

    Ok(())
}
